server:
  port: 8072
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/niittraveluserdb
  application:
    name: package-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
