server:
  port: 8091
#  error:
#    include-stacktrace: never



spring:
  data:
    mongodb:
      database: niittraveluserdb
      uri: mongodb://localhost:27017/
  application:
    name: booking-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true
