package com.stackroute.RegisterService.services;

import com.stackroute.RegisterService.exception.ServiceProviderAlreadyException;
import com.stackroute.RegisterService.exception.ServiceProviderNotFoundException;
import com.stackroute.RegisterService.model.ServiceProvider;

public interface ServiceProviderServie
{
public ServiceProvider registerServiceProvider(ServiceProvider serviceProvider) throws ServiceProviderAlreadyException;
public ServiceProvider updateserviceprovider(ServiceProvider serviceProvider,String email) throws ServiceProviderNotFoundException;
}
