server:
  port: 8082
  error:
    include: always
spring:
  data:
    mongodb:
      database: niittraveluserdb
      uri: mongodb://localhost:27017/
  application:
    name: hotelserviceprovider
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true


